<h1>Add a Meetup</h1>

<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<div class="row">
        <div class='col-sm-4'>
                <?= $this->formRow($form->get('title')) ?>
        </div>
</div>
<br>

<div class="row">
        <div class='col-sm-4'>
                <?= $this->formRow($form->get('description')) ?>
        </div>
</div> 
<br>

<div class="row">
        <div class='col-sm-4'>
                            <?= $this->formRow($form->get('dateStart')) ?>
                            <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                            </span>
        </div>
</div>
    <br>
    <div class="row">
            <div class='col-sm-4'>
                    <?= $this->formRow($form->get('dateEnd')) ?>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
</div>
</div><br>
<?= $this->formInput($form->get('submit')) ?><br>

<?= $this->form()->closeTag($form); ?>
        <script type="text/javascript">
                $(function () {
                        $('#datetimepickerStart').datetimepicker();
                        $('#datetimepickerEnd').datetimepicker();
                });
        </script>
